apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: carservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: serhii128/mssql
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "Qwerty123!"
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: mssql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: carservice
spec:
  type: ClusterIP
  selector:
    app: mssql
  ports:
    - name: sql
      port: 1433
      targetPort: 1433
